Teradata/developer-resources

- .github/workflows/PULL_REQUEST_TEMPLATE.md
- package-lock.json
- package.json
1. Add language selector in the mobile navbar
2. Fix margin issue of mobile navbar in the landing page
> Fix(components): add language selector in mobilenav

- package-lock.json
- package.json
- src/css/custom.css
- src/theme/Admonition/Layout/index.tsx
- src/theme/Admonition/Layout/styles.module.css
Style fixes for Tip, Notes, Code snippet and Secondary menu based on the design review.
- Change styling of Tip, Notes according to the design.
- Add background color to Copy button in code snippets for better visibility.
- Fix caret icon styling in the secondary menu.
- Style content menu according to the design.
> fix(styles): style fixes based on design review

- src/css/custom.css
- Add a trailing icon to external links in docs.
> feat(links): add icon to identify external links

- .github/workflows/deploy.yml
- Use https://github.com/JamesIves/github-pages-deploy-action to deploy the site to github pages.
- Exclude the pr-previews folder from being overwritten when main branch is deployed.
> fix(deployment): use different github action to deploy the site

- .github/workflows/deploy.yml
Add github token to deploy action
> fix(deploy): add github token to deploy action

- package-lock.json
- package.json
- src/theme/CodeBlock/index.tsx
- src/theme/Footer/index.tsx
- src/theme/Navbar/index.tsx
- Updated the react component package to teradata-web/react-components
> fix(components): add updated react components package

- docusaurus.config.js
- package-lock.json
- package.json
Adding Google Analytic tag support
> feat(): adding gtag tracking

- docusaurus.config.js
Fixing a typo for the korean language set.
> fix(i18n): typo fix for korean lang

- src/components/HomepageFeatures/index.js
- src/pages/ai-unlimited.js
- src/theme/Navbar/index.tsx
- Fix translations in ai unlimited docs homepage
- Fix language selector issue in the navbar
> fix(translations): fix ai-unlimited homepage translations

- i18n/en/code.json
- src/components/DevelopersHomepage/FeatureData.js
- src/components/DevelopersHomepage/GetStarted.js
- src/components/DevelopersHomepage/LinksImg.js
- src/components/DevelopersHomepage/TopPicks.js
Added english translations for developers homepage
> english translations for developers home page

- i18n/en/code.json
- src/components/DevelopersHomepage/FeatureData.js
- src/components/DevelopersHomepage/JumpIn.js
- src/components/DevelopersHomepage/styles.module.css
Changed bullet points from images to list to help SEO scores
> fix bullet points

- docusaurus.config.js
> Update CSP URLs in docusaurus.config.js

- package-lock.json
- src/config/header.navitems.js
- src/theme/Navbar/index.tsx
> fix links in navbar

- i18n/en/code.json
> fix it operations title

- docusaurus.config.js
- i18n/de/code.json
- i18n/en/code.json
- i18n/es/code.json
- i18n/fr/code.json
- i18n/ja/code.json
- i18n/ko/code.json
> fix developers homepage title

- i18n/es/code.json
> spanish translations

- package-lock.json
- package.json
- src/components/HomepageFeatures/index.js
- External links in footer and header will open in a new tab
- Fix the issue with list styles in docs
> fix(components): fix navigation issues in header and footer components

- package-lock.json
- package.json
Header in the downloads and developer resources site doesn't look consistent. Update `@teradata-web/react-components` package to have consistent styles.
- Update `@teradata-web/react-components` package
> fix(styles): update react component styles

- quickstarts/_partials/tabsDBTProfiles.mdx
- quickstarts/manage-data/dbt.md
- Fix for https://github.com/Teradata/developer-resources/issues/133
> fix dbt quickstart after migration

- quickstarts/_partials/tabsDBTProfiles.mdx
- quickstarts/manage-data/dbt.md
> fix dbt docs

- quickstarts/vantagecloud-lake/_partials/create-jwt.mdx
> fix the JWT bash code example

- docs/resources/quickstart/docker-install-ai-unlimited-jupyter.md
Fixed typos in the Docker code for AWS and for Azure - in step 1 in Start the Manager and JupyterLab.
See description above.
- [X ] `npm run start` still works.
- [n/a] Any new dependencies have been added to the appropriate files.
n/a
> Fixed code typos in step 1

- i18n/de/code.json
- i18n/en/code.json
- i18n/es/code.json
- i18n/fr/code.json
- i18n/ja/code.json
- i18n/ko/code.json
- package-lock.json
- src/components/HomepageFeatures/Editions.js
- src/components/HomepageFeatures/MicrosoftFabric.js
- src/components/HomepageFeatures/cloud.js
- src/components/HomepageFeatures/index.js
- src/components/HomepageFeatures/styles.module.css
- src/components/SelectComponent/SelectComponent.js
- src/components/SelectComponent/styles.module.css
- src/theme/DocSidebar/index.tsx
- src/theme/DocSidebar/styles.css
- src/theme/Navbar/index.tsx
Select ai unlimited by edition
- New tile under “Featured guides”
- Select edition on article page
- Main page 
- Desktop
- Mobile
> feat(ai-unlimited): editions

- src/components/SelectComponent/SelectComponent.js
- src/theme/Navbar/index.tsx
> fix toc visibility

- package-lock.json
Update teradata web components library
> update teradata web components library

- quickstarts/create-applications/mule-teradata-connector-release-notes.md
Object Store upgradation date in the release notes
> Mulesoft 1.0.6

- i18n/en/code.json
> update TOC title

- i18n/es/docusaurus-plugin-content-docs-quickstarts/current/manage-data/fastload.md
- i18n/ja/docusaurus-plugin-content-docs-quickstarts/current/manage-data/fastload.md
- quickstarts/manage-data/fastload.md
> missing fastload article

- src/theme/SearchBar/styles.css
Algolia search box visibility on mobile or tablet
- One
- Two
- Three
> fix margin of search bar
